language: ruby

matrix:
  include:
    - rvm: 2.1
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails4.2.beta.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.1.gemfile

notifications:
  irc: "irc.freenode.org#projecthydra"

